[package]
name = "binpack2d_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binpack2d = "*"
rand = "0.8.5"
svg_fmt = "0.4.1"
